
services:
  product-service:
    build: ./ProductRestAPIUsingSpringData/
    ports:
      - 80:8080
    depends_on:
      - mysql-service
    restart: always
  mysql-service:
    image: mysql:8.0
    ports:
      - 3307:3306
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=upgrad_db
    restart: always
