spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/jwt_demo_db_test
  application:
    name: jwt-mongo-demo

app:
  jwt:
    secret: mysupersecurejwtsecretkey9876543210
    expiration: 600000 # 3 minute (in ms)
logging:
  level:
    org:
      springframework:
        security: INFO
