services:
  akash-service:
    image: akashkale/my-react-vite:upgrade1
    ports:
      - 81:80
  std1-service:
    image: sharmavikas4/react-app:latest
    ports:
      - 82:80
  std2-service:
    image: himanshukumarjha/my-react-vite:demo1
    ports:
      - 83:80
  std3-service:
    image: sujithanune2607/my_react_vite:sujithademo
    ports:
     - 84:80
